version: '3.1'

services:

  database:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: op_api_prod

  web:
    image: op_api
    restart: always
    ports:
      - 4000:4000
    environment:
      APP_HOST: ${APP_HOST}
      APP_PORT: ${APP_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      PLANARIA_TOKEN: ${PLANARIA_TOKEN}
    depends_on:
      - database